language: python
python:
  - "3.7"
  - "3.8"
  - "nightly"
  
install:
  - pip install .
  
script:
  - python tests/test_suite.py

after_success:
- git config --global user.name "semantic-release (via TravisCI)"
- git config --global user.email "semantic-release@travis"
- pip install python-semantic-release
- semantic-release publish